# Generated by Django 6.1 on 2026-09-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
