# Generated by Django 6.1 on 2026-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Opsional, judul yang muncul di overlay banner', max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.CharField(blank=True, help_text='Opsional, arahkan ke URL tertentu saat banner diklik', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Angka kecil tampil lebih dulu')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
