# Generated by Django 6.1 on 2026-09-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, help_text='Opsional, deskripsi singkat banner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('artikel', 'Artikel/Berita'), ('fiksi', 'Fiksi'), ('event', 'Event'), ('umum', 'Umum')], default='umum', max_length=20),
        ),
    ]
