# Generated by Django 6.1 on 2026-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_banner_description_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
