# Generated by Django 6.1 on 2026-09-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('homepage', 'Halaman Utama'), ('fiction', 'Halaman Fiksi')], default='homepage', max_length=20),
        ),
    ]
