# Generated by Django 6.1 on 2026-10-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_banner_placement'),
        ('interactions', '0004_commentdislikes_commentlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='articles.articles')),
            ],
            options={
                'ordering': ['viewed_at'],
            },
        ),
    ]
