# Generated by Django 6.1 on 2026-10-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_banner_placement'),
        ('reading_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingactivity',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activities', to='articles.articles'),
        ),
    ]
