# Generated by Django 6.0.7 on 2026-07-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
