# Generated by Django 6.1 on 2026-09-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='stories/covers/')),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('romance', 'Romance'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('mystery', 'Mystery'), ('science_fiction', 'Science Fiction'), ('comedy', 'Comedy'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('fantasy', 'Fantasy')], max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Pisahkan tag dengan spasi', max_length=200)),
                ('target_pembaca', models.CharField(choices=[('umum', 'Umum'), ('remaja', 'Remaja'), ('dewasa', 'Dewasa')], default='umum', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu approval'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(limit_choices_to={'status_kontributor': 'approved'}, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fiction.stories')),
            ],
            options={
                'ordering': ['chapter_number'],
                'constraints': [models.UniqueConstraint(fields=('story', 'chapter_number'), name='unique_story_chapter_number')],
            },
        ),
    ]
