# Generated by Django 6.1 on 2026-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0002_stories_is_completed_stories_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
