# Generated by Django 6.1 on 2026-09-22 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0004_chaptercomments_chaptercommentlikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterCommentDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='chaptercommentlikes',
            name='unique_user_comment_like',
        ),
        migrations.AddConstraint(
            model_name='chaptercommentlikes',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_chapter_comment_like'),
        ),
        migrations.AddField(
            model_name='chaptercommentdislikes',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='fiction.chaptercomments'),
        ),
        migrations.AddField(
            model_name='chaptercommentdislikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chaptercommentdislikes',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_chapter_comment_dislike'),
        ),
    ]
